### ISSUE TITLE
Update atleast 5 landmarks for every city present in `cities.json`

### ISSUE THREAD

**Issue by thenishantsapkota** [Know-Nepal/borderlines#16]
There should be atleast 5 landmarks for a specified city.

**Comment by dyaramatreya** [comment]
Hi @thenishantsapkota 
Do you mean, as a part of the PR we must ensure that the json object at https://github.com/Know-Nepal/borderlines/blob/main/data/borderlines.json contains at least 5 landmarks for each of the already added cities?

**Comment by thenishantsapkota** [comment]
Yes that's exactly my intention, atleast there must be 5 landmarks per city @dyaramatreya

**Comment by thenishantsapkota** [comment]
Assigned it to you @dyaramatreya!

**Comment by dyaramatreya** [comment]
@thenishantsapkota Linked the PR #17 . Please review and approve the PR. Thanks
